### ISSUE TITLE
query_poll_table is getting errors when attempting to update table

### ISSUE THREAD

**Issue by brountre** [nirgal/pgsf#1]
(.venv) PS C:\Repos\Code\Python\pgsf> python.exe .\query_poll_table.py Account

Traceback (most recent call last):
  File "C:\Repos\Code\Python\pgsf\query_poll_table.py", line 275, in <module>
    main()
  File "C:\Repos\Code\Python\pgsf\query_poll_table.py", line 273, in main
    sync_table(args.table)
  File "C:\Repos\Code\Python\pgsf\query_poll_table.py", line 232, in sync_table
    pg_merge_update(td, tmp_tablename)
  File "C:\Repos\Code\Python\pgsf\query_poll_table.py", line 141, in pg_merge_update
    cursor.execute(sql)
psycopg2.errors.UndefinedColumn: column "IsDeleted" does not exist
LINE 5:              WHERE NOT "IsDeleted"
                               ^
HINT:  Perhaps you meant to reference the column "tmp_account.isdeleted" or the column "account.isdeleted".

**Comment by nirgal** [comment]
Please make sure the column "IsDeleted" is selected for synchronisation in the csv file.

**Comment by brountre** [comment]
I believe this is set for synchronization.  Please see attached mapping file

[Account.csv](https://github.com/nirgal/pgsf/files/8042192/Account.csv)
